#!/bin/sh
# C:\Users\DUC\scoop\apps\sudo\current\sudo.ps1
if command -v pwsh.exe > /dev/null 2>&1; then
    pwsh.exe -noprofile -ex unrestricted -file "C:\Users\DUC\scoop\apps\sudo\current\sudo.ps1"  "$@"
else
    powershell.exe -noprofile -ex unrestricted -file "C:\Users\DUC\scoop\apps\sudo\current\sudo.ps1"  "$@"
fi